import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'First Next App', // we can write here our app name
  description: 'Generated by create next app', 
} 

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      {children}
      </body>
    </html>
  )
}
